/* (c) Copyright Frontify Ltd., all rights reserved. */

// Generates one docs-only MDX page per SDK guide. The guide markdown is
// rendered at runtime via the <Markdown> block (never parsed as MDX), so
// arbitrary markdown content is safe.

import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { guides } from '@frontify/fondue-sdk';

const outDir = join(dirname(fileURLToPath(import.meta.url)), '../stories');

/**
 * Turns a guide id directory into a human-readable sidebar group label,
 * e.g. "getting-started" → "Getting started".
 * @param {string} dir
 */
const toGroupLabel = (dir) => {
    const spaced = dir.replaceAll('-', ' ');
    return spaced.charAt(0).toUpperCase() + spaced.slice(1);
};

/**
 * Builds the Storybook sidebar title for a guide entirely from its id
 * (e.g. "getting-started/Setup" → "Getting started/Setup"), so both the group
 * and the leaf name are stable regardless of what the SDK puts in `guide.title`.
 * @param {import('@frontify/fondue-sdk').Guide} guide
 */
const storyTitle = (guide) => {
    const separatorIndex = guide.id.lastIndexOf('/');
    if (separatorIndex === -1) {
        return guide.id;
    }
    const group = toGroupLabel(guide.id.slice(0, separatorIndex));
    const name = guide.id.slice(separatorIndex + 1);
    return `${group}/${name}`;
};

/**
 * @param {import('@frontify/fondue-sdk').Guide} guide
 * @param {string} title
 */
const template = (guide, title) => `{/* (c) Copyright Frontify Ltd., all rights reserved. */}

{/* Generated by scripts/generateGuideStories.mjs — do not edit. */}

import { Markdown, Meta } from '@storybook/addon-docs/blocks';
import { guides } from '@frontify/fondue-sdk';

<Meta title="${title.replaceAll('"', '&quot;')}" />

<Markdown>{guides.get('${guide.id}')?.content ?? ''}</Markdown>
`;

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

for (const guide of guides.list()) {
    const title = storyTitle(guide);
    const outFile = join(outDir, `${title}.mdx`);
    mkdirSync(dirname(outFile), { recursive: true });
    writeFileSync(outFile, template(guide, title));
}

console.log(`Generated ${guides.size} guide docs page(s) in stories/`);
