/* (c) Copyright Frontify Ltd., all rights reserved. */

// Generates one docs-only MDX page per SDK guide. The guide markdown is
// rendered at runtime via the <Markdown> block (never parsed as MDX), so
// arbitrary markdown content is safe.

import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { guides } from '@frontify/fondue-sdk';

const outDir = join(dirname(fileURLToPath(import.meta.url)), '../stories');

/** @param {import('@frontify/fondue-sdk').Guide} guide */
const template = (guide) => `{/* (c) Copyright Frontify Ltd., all rights reserved. */}

{/* Generated by scripts/generateGuideStories.mjs — do not edit. */}

import { Markdown, Meta } from '@storybook/addon-docs/blocks';
import { guides } from '@frontify/fondue-sdk';

<Meta title="${guide.title.replaceAll('"', '&quot;')}" />

<Markdown>{guides.get('${guide.id}')?.content ?? ''}</Markdown>
`;

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

for (const guide of guides.list()) {
    const outFile = join(outDir, `${guide.title}.mdx`);
    mkdirSync(dirname(outFile), { recursive: true });
    writeFileSync(outFile, template(guide));
}

console.log(`Generated ${guides.size} guide docs page(s) in stories/`);
