packages:
    - packages/*
    - storybook-docs

allowBuilds:
    "@bundled-es-modules/glob": true
    "@parcel/watcher": true
    cypress: true
    esbuild: true
    style-dictionary: true
    unrs-resolver: true

blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
    - "@frontify/*"

publicHoistPattern:
    - "*eslint*"
    - "*prettier*"
    - "*tailwind*"

confirmModulesPurge: false
