packages:
  - packages/*
  - storybook-docs

onlyBuiltDependencies:
  - cypress
  - esbuild
  - unrs-resolver

patchedDependencies:
  '@udecode/plate-core': patches/@udecode__plate-core.patch

prefer-workspace-packages: true
