packages:
  - packages/*
  - storybook-docs

allowBuilds:
  "@bundled-es-modules/glob": true
  "@parcel/watcher": true
  cypress: true
  esbuild: true
  style-dictionary: true
  unrs-resolver: true

blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@frontify/*"
  # Renovate security update: style-dictionary@5.4.4
  - style-dictionary@5.4.4

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
  - "*tailwind*"

confirmModulesPurge: false
