packages:
  - packages/*
  - storybook-docs

onlyBuiltDependencies:
  - '@bundled-es-modules/glob'
  - '@parcel/watcher'
  - cypress
  - esbuild
  - style-dictionary
  - unrs-resolver

prefer-workspace-packages: true
