/* (c) Copyright Frontify Ltd., all rights reserved. */

/**
 * What the picker offers, as glyph and searchable name. Bundled rather than
 * pulled from a data package — a spike does not need ten thousand of them.
 * Names carry every word worth searching for, since matching is per word.
 */
export const EMOJIS: [glyph: string, name: string][] = [
    ['😀', 'grinning'],
    ['😃', 'smiley'],
    ['😄', 'smile'],
    ['😁', 'grin'],
    ['😂', 'joy'],
    ['🙂', 'slightly smiling'],
    ['😉', 'wink'],
    ['😊', 'blush'],
    ['😍', 'heart eyes'],
    ['😘', 'kiss'],
    ['😎', 'sunglasses cool'],
    ['🤔', 'thinking'],
    ['🤗', 'hugs'],
    ['🤩', 'star struck'],
    ['😐', 'neutral'],
    ['😴', 'sleeping'],
    ['😢', 'cry'],
    ['😭', 'sob'],
    ['😅', 'sweat smile'],
    ['😬', 'grimacing'],
    ['😳', 'flushed'],
    ['🥳', 'partying'],
    ['🤯', 'mind blown'],
    ['😤', 'triumph'],
    ['😱', 'scream'],
    ['🙃', 'upside down'],
    ['🤷', 'shrug'],
    ['🙌', 'raised hands'],
    ['👏', 'clap'],
    ['👍', 'thumbs up'],
    ['👎', 'thumbs down'],
    ['👌', 'ok hand'],
    ['🤝', 'handshake'],
    ['🙏', 'pray thanks'],
    ['💪', 'muscle'],
    ['✌️', 'victory peace'],
    ['👀', 'eyes'],
    ['🧠', 'brain'],
    ['❤️', 'heart red'],
    ['🧡', 'heart orange'],
    ['💚', 'heart green'],
    ['💙', 'heart blue'],
    ['💜', 'heart purple'],
    ['🖤', 'heart black'],
    ['💔', 'broken heart'],
    ['✨', 'sparkles'],
    ['🌟', 'star glowing'],
    ['⭐', 'star'],
    ['🔥', 'fire'],
    ['💥', 'boom'],
    ['🎉', 'tada party'],
    ['🎊', 'confetti'],
    ['🎂', 'cake birthday'],
    ['🎁', 'gift'],
    ['🏆', 'trophy'],
    ['🥇', 'first place medal'],
    ['🚀', 'rocket ship'],
    ['✅', 'check mark done'],
    ['☑️', 'checkbox'],
    ['❌', 'cross wrong'],
    ['⚠️', 'warning'],
    ['❓', 'question'],
    ['❗', 'exclamation'],
    ['💡', 'bulb idea'],
    ['📌', 'pushpin'],
    ['📎', 'paperclip'],
    ['📝', 'memo note'],
    ['📄', 'page document'],
    ['📊', 'bar chart'],
    ['📈', 'chart increasing'],
    ['📉', 'chart decreasing'],
    ['📅', 'calendar'],
    ['⏰', 'alarm clock'],
    ['⏳', 'hourglass'],
    ['🔍', 'magnifying glass search'],
    ['🔒', 'lock'],
    ['🔑', 'key'],
    ['🔧', 'wrench'],
    ['🛠️', 'tools'],
    ['🐛', 'bug'],
    ['💻', 'laptop computer'],
    ['🖥️', 'desktop'],
    ['📱', 'mobile phone'],
    ['⌨️', 'keyboard'],
    ['🖨️', 'printer'],
    ['💾', 'floppy save'],
    ['🗑️', 'wastebasket delete'],
    ['📦', 'package'],
    ['✉️', 'envelope mail'],
    ['📢', 'loudspeaker announce'],
    ['🔔', 'bell'],
    ['🎨', 'art palette'],
    ['🎯', 'target dart'],
    ['🧩', 'puzzle'],
    ['🗺️', 'map'],
    ['🌍', 'earth globe'],
    ['☀️', 'sun'],
    ['🌙', 'moon'],
    ['☁️', 'cloud'],
    ['🌧️', 'rain'],
    ['❄️', 'snowflake'],
    ['🌱', 'seedling'],
    ['🌳', 'tree'],
    ['🌸', 'blossom'],
    ['🍀', 'four leaf clover luck'],
    ['☕', 'coffee'],
    ['🍕', 'pizza'],
    ['🍺', 'beer'],
    ['🥂', 'cheers'],
    ['🍎', 'apple'],
    ['🐱', 'cat'],
    ['🐶', 'dog'],
    ['🦄', 'unicorn'],
    ['🐢', 'turtle slow'],
    ['🚗', 'car'],
    ['✈️', 'airplane'],
    ['🏠', 'house'],
    ['🏢', 'office building'],
];

/** Word-prefix matching, so `:tha` finds "pray thanks" but `:ank` does not. */
export const matches = (name: string, query: string): boolean =>
    query === '' || name.split(' ').some((word) => word.startsWith(query));
