/* (c) Copyright Frontify Ltd., all rights reserved. */

/**
 * Build-time data generation for @frontify/fondue-docs.
 *
 * Reads the manifests exported by the upstream @frontify/fondue-* packages
 * and emits a single TypeScript module that vite will bundle. Icons are
 * synthesized into the components list here so the runtime API has only
 * one entity kind to deal with.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

interface ComponentIndexEntry {
    name: string;
    description: string;
    status: string;
    category: string;
    tags: string[];
    subComponentNames: string[];
    manifestPath: string;
}

interface IconEntry {
    name: string;
    description: string;
    componentName: string;
    importStatement: string;
    filled: boolean;
    availableSizes: number[];
    defaultSize: number;
    tags: string[];
    examples: unknown[];
}

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));

const componentsIndex = require('@frontify/fondue-components/manifests/manifest') as {
    components: Record<string, ComponentIndexEntry>;
};
const icons = require('@frontify/fondue-icons/manifest.json') as { icons: IconEntry[] };
const tokens = require('@frontify/fondue-tokens/manifest.json') as { tokens: unknown[]; utilities?: unknown[] };

const realComponents = Object.values(componentsIndex.components).map((entry) => {
    const stem = entry.manifestPath.replace(/\.json$/i, '');
    const detail = require(`@frontify/fondue-components/manifests/${stem}`) as Record<string, unknown>;
    return { ...detail, subComponentNames: entry.subComponentNames };
});

const iconComponents = icons.icons.map((icon) => ({
    name: icon.componentName,
    description: icon.description,
    status: '',
    category: 'icon',
    tags: icon.tags,
    subComponentNames: [],
    relatedComponents: [],
    importStatement: icon.importStatement,
    instructions: '',
    props: [],
    subComponents: [],
    examples: icon.examples,
    typeDefinitions: {},
}));

const components = [...realComponents, ...iconComponents];
const stringify = (value: unknown): string => JSON.stringify(value, null, 4);

const outPath = join(__dirname, '../src/__generated__/data.ts');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
    outPath,
    `/* (c) Copyright Frontify Ltd., all rights reserved. */
/* @generated by scripts/generateData.ts — do not edit by hand. */

import { type ComponentDetails } from '../types/components';
import { type Token, type TokenUtility } from '../types/tokens';

export const components: readonly ComponentDetails[] = ${stringify(components)};
export const tokens: readonly Token[] = ${stringify(tokens.tokens)};
export const tokenUtilities: readonly TokenUtility[] = ${stringify(tokens.utilities ?? [])};
`,
);

console.log(
    `✓ ${realComponents.length} components + ${iconComponents.length} icons, ` +
        `${tokens.tokens.length} tokens, ${tokens.utilities?.length ?? 0} utilities`,
);
