/* (c) Copyright Frontify Ltd., all rights reserved. */

/**
 * Extra search terms for icons, keyed by icon name (the folder name in `icons/`, without the `-filled` suffix).
 *
 * The icon names describe what the glyph shows (`cog`, `magnifier`), while people usually search for what it
 * means (`settings`, `search`). These terms are merged into the manifest `tags` next to the words of the name.
 * Filled variants inherit the terms of their outline icon.
 */
export const ICON_SYNONYMS: Record<string, string[]> = {
    archive: ['storage', 'box'],
    'arrow-circle-down': ['download'],
    'arrow-circle-up': ['upload'],
    'arrow-expand': ['fullscreen', 'maximize', 'enlarge'],
    'arrow-left': ['back', 'previous'],
    'arrow-minimize': ['exit-fullscreen', 'shrink'],
    'arrow-move': ['drag', 'reposition'],
    'arrow-out-external': ['external', 'external-link', 'open-in-new'],
    'arrow-out-logout': ['logout', 'log-out', 'sign-out', 'exit'],
    'arrow-out-share': ['share', 'export'],
    'arrow-right': ['next', 'forward'],
    'arrow-round-anti-clockwise': ['undo', 'reset', 'revert'],
    'arrow-round-clockwise': ['redo', 'refresh', 'reload'],
    'arrow-swap': ['switch', 'exchange'],
    'arrow-sync': ['sync', 'refresh', 'reload', 'update'],
    bell: ['notification', 'notifications', 'alert', 'reminder'],
    bookmark: ['save', 'saved', 'favorite'],
    buildings: ['company', 'organization', 'office', 'enterprise'],
    calendar: ['date', 'schedule', 'event'],
    'calendar-checked': ['date', 'scheduled', 'event'],
    camera: ['photo', 'picture', 'capture'],
    'caret-down': ['chevron', 'dropdown', 'expand', 'open'],
    'caret-left': ['chevron', 'back', 'previous'],
    'caret-right': ['chevron', 'next', 'forward'],
    'caret-up': ['chevron', 'collapse', 'close'],
    'caret-up-down': ['chevron', 'sort', 'select'],
    'chart-bars': ['analytics', 'statistics', 'graph', 'report'],
    'chart-line': ['analytics', 'statistics', 'graph', 'trend'],
    'chart-pie': ['analytics', 'statistics', 'graph'],
    'check-mark': ['done', 'confirm', 'ok', 'success', 'tick', 'complete'],
    'check-mark-circle': ['done', 'confirm', 'ok', 'success', 'complete', 'verified'],
    clipboard: ['copy', 'paste'],
    clock: ['time', 'history', 'recent'],
    'cloud-arrow-down': ['download'],
    'cloud-arrow-up': ['upload'],
    'cloud-off': ['offline', 'disconnected'],
    code: ['developer', 'source', 'html'],
    cog: ['settings', 'gear', 'preferences', 'configuration', 'options'],
    'color-fan': ['palette', 'swatches', 'colors'],
    'command-line-box': ['terminal', 'console', 'shell'],
    country: ['globe', 'world', 'region', 'international'],
    cross: ['close', 'dismiss', 'cancel', 'remove', 'x', 'delete'],
    'cross-circle': ['close', 'clear', 'cancel', 'error', 'remove'],
    'cursor-click': ['click', 'select', 'pointer'],
    'device-laptop': ['computer', 'notebook'],
    'device-monitor': ['desktop', 'screen', 'display'],
    'device-printer': ['print'],
    devices: ['responsive', 'mobile', 'desktop'],
    document: ['file', 'page'],
    'document-text': ['file', 'page', 'text', 'article'],
    'dots-horizontal': ['more', 'menu', 'options', 'ellipsis', 'overflow', 'actions'],
    'dots-vertical': ['more', 'menu', 'options', 'kebab', 'overflow', 'actions'],
    droplet: ['color', 'fill', 'ink'],
    envelope: ['email', 'mail', 'message', 'inbox'],
    eraser: ['clear', 'erase'],
    'exclamation-mark': ['warning', 'important', 'alert'],
    'exclamation-mark-circle': ['error', 'alert', 'warning', 'danger'],
    'exclamation-mark-triangle': ['warning', 'caution', 'alert', 'danger', 'error'],
    eye: ['show', 'visible', 'view', 'preview', 'visibility'],
    'eye-off': ['hide', 'hidden', 'invisible', 'visibility'],
    'face-happy': ['emoji', 'smile', 'satisfied'],
    'face-sad': ['emoji', 'unhappy', 'dissatisfied'],
    flag: ['report', 'mark'],
    folder: ['directory', 'collection'],
    'folder-plus': ['new-folder', 'create', 'add'],
    funnel: ['filter'],
    'grab-handle': ['drag', 'reorder', 'move', 'handle'],
    h: ['heading', 'title'],
    home: ['house', 'start', 'dashboard'],
    image: ['picture', 'photo', 'media'],
    info: ['information', 'about', 'details', 'help'],
    label: ['tag'],
    language: ['translate', 'translation', 'locale', 'i18n', 'globe'],
    layers: ['stack', 'levels'],
    lightbulb: ['idea', 'tip', 'hint'],
    lightning: ['flash', 'fast', 'power', 'energy'],
    link: ['url', 'hyperlink', 'chain'],
    'list-bullet': ['list', 'unordered-list'],
    'list-numbers': ['list', 'ordered-list', 'numbered-list'],
    'lock-closed': ['locked', 'lock', 'secure', 'private', 'password'],
    'lock-open': ['unlocked', 'unlock', 'public'],
    magnifier: ['search', 'find', 'lookup', 'zoom'],
    'magnifier-minus': ['zoom-out'],
    'magnifier-plus': ['zoom-in'],
    'map-pointer': ['location', 'place', 'address', 'map'],
    megaphone: ['announcement', 'marketing', 'broadcast'],
    microphone: ['voice', 'record', 'audio'],
    minus: ['remove', 'subtract', 'decrease', 'collapse'],
    'minus-circle': ['remove', 'subtract', 'decrease'],
    money: ['price', 'payment', 'currency', 'cost'],
    'music-note': ['audio', 'sound'],
    paintbrush: ['style', 'design', 'paint'],
    paperclip: ['attachment', 'attach'],
    paperplane: ['send', 'submit'],
    pen: ['edit', 'write', 'rename', 'pencil'],
    people: ['users', 'team', 'group', 'members'],
    person: ['user', 'account', 'profile', 'avatar', 'member'],
    'person-anonymous': ['guest', 'anonymous', 'user'],
    'person-lock': ['permissions', 'access', 'user'],
    'person-slash': ['blocked', 'banned', 'user'],
    pin: ['pinned', 'location'],
    play: ['start', 'video', 'media'],
    plus: ['add', 'create', 'new', 'increase', 'expand'],
    'plus-circle': ['add', 'create', 'new'],
    puzzle: ['plugin', 'extension', 'integration', 'add-on'],
    'question-mark': ['help', 'faq', 'support'],
    'question-mark-circle': ['help', 'faq', 'support', 'info'],
    rocket: ['launch', 'release', 'deploy'],
    scissors: ['cut'],
    sparks: ['ai', 'magic', 'generate', 'new'],
    speaker: ['sound', 'volume', 'audio'],
    'speaker-off': ['mute', 'muted', 'silent', 'sound'],
    'speech-bubble-dots': ['comment', 'chat', 'message', 'typing'],
    'speech-bubble-empty': ['comment', 'chat', 'message', 'feedback'],
    'speech-bubble-quote': ['comment', 'quote', 'testimonial'],
    'speech-bubble-stack': ['comments', 'chat', 'messages', 'conversation'],
    star: ['favorite', 'rating', 'bookmark'],
    suitcase: ['work', 'business', 'job'],
    table: ['grid', 'spreadsheet'],
    target: ['goal', 'focus', 'aim'],
    'thumbs-down': ['dislike', 'reject', 'disapprove'],
    'thumbs-up': ['like', 'approve', 'agree'],
    'trash-bin': ['delete', 'remove', 'bin', 'garbage', 'discard'],
    typography: ['font', 'text'],
    wand: ['magic', 'ai', 'auto'],
};

/** Words in icon names that carry no search value on their own (e.g. `media-object-ratio-1-to-1`). */
export const IGNORED_NAME_PARTS = new Set(['a', 'an', 'and', 'in', 'of', 'the', 'to', 'with']);
