/* (c) Copyright Frontify Ltd., all rights reserved. */

/**
 * Build-time data generation for @frontify/fondue-sdk.
 *
 * The generators in scripts/generate/ read the manifests exported by the
 * upstream @frontify/fondue-* packages, and this script emits the TypeScript
 * modules that vite will bundle:
 *
 *   - src/__generated__/data.ts    — the full data snapshot
 *   - src/__generated__/unions.ts  — literal unions derived from the data
 *     (statuses, categories) so typos in filters fail at compile time.
 *
 * The whole snapshot is validated — the build fails on missing
 * statuses/categories, dangling cross-references, or duplicate ids, so the
 * runtime never has to.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { generateComponents } from './generate/components';
import { generateGuides } from './generate/guides';
import { generateTokens } from './generate/tokens';

const __dirname = dirname(fileURLToPath(import.meta.url));

const { components, realCount, iconCount, errors: componentErrors } = generateComponents();
const { tokens, tokenUtilities, errors: tokenErrors } = generateTokens();
const { guides, errors: guideErrors } = generateGuides();

// ─── Validation ─────────────────────────────────────────────────────────────
// Fail the build on inconsistent data so the runtime can rely on it.

const errors = [...componentErrors, ...tokenErrors, ...guideErrors];
if (errors.length > 0) {
    console.error(`✗ Data validation failed with ${errors.length} error(s):`);
    for (const error of errors) {
        console.error(`  - ${error}`);
    }
    process.exit(1);
}

// ─── Emission ───────────────────────────────────────────────────────────────

const stringify = (value: unknown): string => JSON.stringify(value, null, 4);

const outPath = join(__dirname, '../src/__generated__/data.ts');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
    outPath,
    `/* (c) Copyright Frontify Ltd., all rights reserved. */
/* @generated by scripts/generateData.ts — do not edit by hand. */

import { type ComponentDetails } from '../types/components';
import { type Guide } from '../types/guides';
import { type Token, type TokenUtility } from '../types/tokens';

export const components: readonly ComponentDetails[] = ${stringify(components)};
export const tokens: readonly Token[] = ${stringify(tokens.tokens)};
export const tokenUtilities: readonly TokenUtility[] = ${stringify(tokens.utilities ?? [])};
export const guides: readonly Guide[] = ${stringify(guides)};
`,
);

console.log(
    `✓ ${realCount} components + ${iconCount} icons, ` +
        `${tokens.length} tokens, ${tokenUtilities.length} utilities, ` +
        `${guides.length} guides`,
);
